### ISSUE TITLE
Develop Responsive Landing Page Layout

### ISSUE THREAD

**Issue by DiyaVj** [MLSA-WGMIT/WGMIT-Website#3]
Implement a responsive layout for the landing page of the WGMIT website. Ensure that the page looks and functions seamlessly across various devices and screen sizes. Your coding skills will play a crucial role in delivering a user-friendly experience.

**Comment by Adijainy** [comment]
can we use tailwind css or just stick to vanilla css?

**Comment by Adijainy** [comment]
can you please assign this issue to me

**Comment by DiyaVj** [comment]
Done @Adijainy ! Regarding the choice between Tailwind CSS and vanilla CSS, we're open to whichever option our contributors are most comfortable with.

**Comment by DiyaVj** [comment]
Thanks @Adijainy ! It looks good. Now we can create separate issues for each section of the website so that there are possibilities for others to contribute as well :)
