### ISSUE TITLE
"About Us" and "Our Mission" Section

### ISSUE THREAD

**Issue by Olorunshogo** [MLSA-WGMIT/WGMIT-Website#9]
**Is your feature request related to a WGMIT? Please describe.**
I just checked the website and found out that the About Us and the Our Mission section is not yet there. 

**Describe the solution you'd like**
Although I'm still new to working and interpreting Figma files, I am hoping to get a friend to help with my inadequate knowledge and code the two sections since it's yet to be done.

**Describe alternatives you've considered**
None for now.

**Additional context**
With time, I hope to do more than these two sections.

**Comment by Olorunshogo** [comment]
In retrospect, I think I know how to fill out this form now. I'm expected to give more details than I gave already.

Using HTML, I intend to make the structure for the sections and also to style using CSS. Where necessary and upon availability, I will also make the two sections that I've made to be responsive to table and mobile screen sizes.

**Comment by DiyaVj** [comment]
Great @Olorunshogo, I am assigning this issue to you. Looking forward to your contribution. Good Luck!✨

**Comment by Olorunshogo** [comment]
I'm done with the sections and made it responsive to different devices and screen sizes. I'm trying to push it to main branch but, I'm getting a response that I'm not permitted to do that. I forked it and pushed all my commits to it. 

Thanks

**Comment by DiyaVj** [comment]
Kudos @Olorunshogo, Thank you for your contribution. So, now that you have made all the changes on your forked repo, you can now create a pull request and once reviewed we can merge it into the main branch.

Dropping this video for your reference: https://youtu.be/8lGpZkjnkt4?si=1CqnBk-LyZfe2q_6

**Comment by Olorunshogo** [comment]
Thanks. I'll work on it as soon as possible.
